In [1]:
import numpy as np
from sklearn.decomposition import PCA

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 232 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 232 from PyObject


In [4]:
X = np.array([[-1, -1], [-2, -1],[-3, -2], [1, 1], [2, 1], [3, 2]])

In [5]:
pca = PCA(n_components=2)
pca.fit(X)

PCA(n_components=2)

In [6]:
print(pca.fit_transform(X))

[[ 1.38340578  0.2935787 ]
 [ 2.22189802 -0.25133484]
 [ 3.6053038   0.04224385]
 [-1.38340578 -0.2935787 ]
 [-2.22189802  0.25133484]
 [-3.6053038  -0.04224385]]


In [7]:
print(pca.explained_variance_ratio_)

[0.99244289 0.00755711]


In [9]:
print(pca.singular_values_)

[6.30061232 0.54980396]


In [10]:
import pandas as pd
import scipy.linalg as la

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 232 from PyObject


In [12]:
# make data
data = np.matrix([[1,2,4], [4,1,2], [5,4,8]])
df = pd.DataFrame(data)
df

0  1  2
0  1  2  4
1  4  1  2
2  5  4  8

In [14]:
# manual calculation

# standardize data
standarized_data = (df - df.mean()) / df.std()
print("Standarized data: ")
print(standarized_data)

Standarized data: 
          0         1         2
0 -1.120897 -0.218218 -0.218218
1  0.320256 -0.872872 -0.872872
2  0.800641  1.091089  1.091089


In [16]:
# Fnding covariance matrix
print(standarized_data.T)
covariance = np.cov(standarized_data.T, bias = 1)
print("Covariance matrix: ")
print(covariance)

          0         1         2
0 -1.120897  0.320256  0.800641
1 -0.218218 -0.872872  1.091089
2 -0.218218 -0.872872  1.091089
Covariance matrix: 
[[0.66666667 0.27954262 0.27954262]
 [0.27954262 0.66666667 0.66666667]
 [0.27954262 0.66666667 0.66666667]]


In [18]:
# Finding eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(covariance)
print("Eigenvalues: ")
print(eigenvalues.round(2))
print("Eigenvectors: ")
print(eigenvectors.round(2))

Eigenvalues: 
[ 1.52  0.48 -0.  ]
Eigenvectors: 
[[ 0.42  0.91 -0.  ]
 [ 0.64 -0.3  -0.71]
 [ 0.64 -0.3   0.71]]


In [22]:
# Finding PCA
n_components = 3
pca_manual = np.matmul(np.array(standarized_data), eigenvectors)
pca_manual = pca_manual[:, :n_components]
print("PCA manual: ")
print(pca_manual.round(2))

PCA manual: 
[[-0.75 -0.89  0.  ]
 [-0.98  0.81 -0.  ]
 [ 1.74  0.08  0.  ]]


In [24]:
# Menggunakan sklearn
pca_sklearn = PCA(n_components=3)
pca_sklearn.fit_transform(standarized_data)
print("PCA sklearn: ")
print(pca_sklearn.fit_transform(standarized_data).round(2))

PCA sklearn: 
[[-0.75  0.89  0.  ]
 [-0.98 -0.81  0.  ]
 [ 1.74 -0.08  0.  ]]
