In [19]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import cross_val_score
from numpy import mean

In [15]:
# make dataset
X, y = make_classification(n_samples=1000, n_features=5, n_informative=5, n_redundant=0, random_state=1)
print(X)
print(y)

[[ 2.39324489 -5.77732048 -0.59062319 -2.08095322  1.04707034]
 [-0.45820294  1.94683482 -2.46471441  2.36590955 -0.73666725]
 [ 2.35162422 -1.00061698 -0.5946091   1.12531096 -0.65267587]
 ...
 [ 2.75687956  1.67376262  0.39299534  1.98033054  1.05085815]
 [-0.3257538   0.86766186 -0.53730065  0.70964207  1.25200457]
 [-1.73912165  0.17810134 -3.28309556 -0.42392359 -3.73900435]]
[1 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 0 1 0 0 1
 1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0
 1 1 1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 1 1 1 0 0 0 1 0 0 0 0 0
 1 1 0 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 1 0 0 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 0 0 1 1 1 1
 1 1 1 0 0 1 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 1 0 0 1 1
 1 0 1 0 0 0 0 1 0 1 1 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 1 1 1 1 0 1 1 1 0 1 0
 1 1 0 1 0 1 1 1 1 0 0 1 0 1 0 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 0 0 1 1 0
 0 1 0 1 0 1 1 0

In [17]:
# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print("Train data : ", len(X_train))
print("Test data : ", len(X_test))

Train data :  800
Test data :  200


In [24]:
from sklearn.linear_model import Perceptron
from sklearn.model_selection import GridSearchCV

clfPerceptron = Perceptron(tol=0.0001, random_state=0, max_iter=10000)

# mendefinisikan model evaluasi
cv = RepeatedStratifiedKFold(n_splits = 10, n_repeats = 3, random_state=1)

# define grid
grid = dict()
grid['eta0'] = [0.0001,0.001, 0.01, 0.1, 1.0]

search = GridSearchCV(clfPerceptron, grid, scoring='accuracy', cv=cv, n_jobs=-1)

result = search.fit(X_train, y_train)
print("Akurasi rata-rata = %.3f" %result.best_score_)
print("Config: %s" %result.best_params_)

means = result.cv_results_['mean_test_score']
params = result.cv_results_['params']

for mean, param in zip(means, params):
    print(">%.3f with %r" % (mean, param))

print(result.best_score_)
print(result.cv_results_['split0_test_score'])

# mengevaluasi model
# scores = cross_val_score(clfPerceptron, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1)
# print(scores)

Akurasi rata-rata = 0.757
Config: {'eta0': 0.01}
>0.742 with {'eta0': 0.0001}
>0.755 with {'eta0': 0.001}
>0.757 with {'eta0': 0.01}
>0.755 with {'eta0': 0.1}
>0.755 with {'eta0': 1.0}
0.7575
[0.825 0.825 0.65  0.65  0.65 ]


In [20]:
# nilai rata-rata akurasi dari 10 x 3 experiment
print("Accuracy Rata-rata = %.3f" %(mean(scores)))

Accuracy Rata-rata = 0.755


In [13]:
print(clfPerceptron.score(X_test, y_test))

0.74
